# Generated by Django 5.2.10 on 2026-04-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
